# Generated by Django 3.2.9 on 2021-12-02 15:41

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shopPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('title', models.CharField(max_length=200)),
                ('prize', models.DecimalField(decimal_places=2, max_digits=4)),
                ('des', models.TextField()),
                ('recstore', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
