# Generated by Django 3.2.9 on 2021-11-25 10:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogs_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
