# Generated by Django 3.2.9 on 2021-12-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listcat', '0002_auto_20211202_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='listcats',
            name='temperament',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
