# Generated by Django 3.2.9 on 2021-12-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listcat', '0004_auto_20211202_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listcats',
            name='prize',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='listcats',
            name='weight',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
